# Frontend Deployment Workflow
name: Deploy Frontend

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main

jobs:
  frontend-deploy:
    name: Deploy Frontend to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install Node.js dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Sync to S3
        run: |
          aws s3 sync ./frontend/build s3://vector-hubspot --delete

      - name: Configure S3 bucket for static web hosting
        run: |
          aws s3 website s3://vector-hubspot --index-document index.html --error-document index.html
